require("__planet-rabbasca__.api")
require("api")

require("prototypes.mod-data")
require("prototypes.map-gen")
require("prototypes.items")
require("prototypes.entities")
require("prototypes.resources")
require("prototypes.surfaces")
require("prototypes.recipes")
require("prototypes.tiles")
require("prototypes.technologies")
require("prototypes.technologies-run")
require("prototypes.tips-and-tricks")
require("prototypes.warp-locations")
require("prototypes.sounds")
require("prototypes.insanity")

require("compatibility.lignumis")
-- require("compatibility.auto-deconstruct") TODO